#!/bin/sh

file=$1
shift
options=$@

BASEDIR=test/bytecode_1.5
#BASEDIR=test/bytecode_2.0
#BASEDIR=test/bytecode_2.1
#BASEDIR=test/bytecode_2.2

if [ `dirname $file` == '.' ] ; then
    file=$BASEDIR/test_$file.pyc
fi

python -u ./scripts/uncompyle $options $file 2>&1 |less
